import numpy as np
import nltk
import string
import os
import sys
import traceback
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from flask import Flask, request, jsonify
from flask_cors import CORS

# Download NLTK data at startup
try:
    nltk.download('punkt', quiet=True)
    nltk.download('stopwords', quiet=True)
    nltk.download('punkt_tab', quiet=True)
except Exception as e:
    print(f"Error downloading NLTK data: {e}")

# Training data structure: (user_input, category, expense_type)
training_data = [

    # Bills & Utilities entries
    ("Meralco bill payment", "Bills & Utilities", "Electricity"),
    ("Monthly electricity charge", "Bills & Utilities", "Electricity"),
    ("Kuryente bill at home", "Bills & Utilities", "Electricity"),
    ("Power meter payment", "Bills & Utilities", "Electricity"),
    ("Electricity utility bill", "Bills & Utilities", "Electricity"),
    ("Bayad kuryente sa buwan", "Bills & Utilities", "Electricity"),
    ("Electric company invoice", "Bills & Utilities", "Electricity"),
    ("Residential power bill", "Bills & Utilities", "Electricity"),
    ("Kontador ng kuryente", "Bills & Utilities", "Electricity"),
    ("Electric service charge", "Bills & Utilities", "Electricity"),
    ("kuryente payment", "Bills & Utilities", "Electricity"),
    ("electricity bill", "Bills & Utilities", "Electricity"),
    ("power bill payment", "Bills & Utilities", "Electricity"),
    ("utility bill electric", "Bills & Utilities", "Electricity"),
    ("bayad kuryente", "Bills & Utilities", "Electricity"),
    ("bayad ilaw", "Bills & Utilities", "Electricity"),
    ("kontador kuryente", "Bills & Utilities", "Electricity"),
    ("quarterly electricity payment", "Bills & Utilities", "Electricity"),
    ("monthly power consumption", "Bills & Utilities", "Electricity"),
    ("singilin sa kuryente", "Bills & Utilities", "Electricity"),
    ("electric metre reading", "Bills & Utilities", "Electricity"),
    ("ilaw sa bahay bayarin", "Bills & Utilities", "Electricity"),
    ("koryente bill", "Bills & Utilities", "Electricity"),
    ("electric power charge", "Bills & Utilities", "Electricity"),
    ("singil sa elektrisidad", "Bills & Utilities", "Electricity"),
    ("Maynilad water bill", "Bills & Utilities", "Water"),
    ("Manila Water payment", "Bills & Utilities", "Water"),
    ("Water meter reading", "Bills & Utilities", "Water"),
    ("Monthly water bill", "Bills & Utilities", "Water"),
    ("Water utility charge", "Bills & Utilities", "Water"),
    ("Bayad tubig", "Bills & Utilities", "Water"),
    ("Kontador ng tubig", "Bills & Utilities", "Water"),
    ("Water service fee", "Bills & Utilities", "Water"),
    ("tubig payment", "Bills & Utilities", "Water"),
    ("water bill", "Bills & Utilities", "Water"),
    ("water meter", "Bills & Utilities", "Water"),
    ("utility bill water", "Bills & Utilities", "Water"),
    ("bayad tubig", "Bills & Utilities", "Water"),
    ("kontador tubig", "Bills & Utilities", "Water"),
    ("quarterly water payment", "Bills & Utilities", "Water"),
    ("monthly water consumption", "Bills & Utilities", "Water"),
    ("PLDT internet bill", "Bills & Utilities", "Internet"),
    ("Globe fiber payment", "Bills & Utilities", "Internet"),
    ("Converge monthly", "Bills & Utilities", "Internet"),
    ("Sky broadband", "Bills & Utilities", "Internet"),
    ("Internet service fee", "Bills & Utilities", "Internet"),
    ("Bayad internet", "Bills & Utilities", "Internet"),
    ("Monthly internet", "Bills & Utilities", "Internet"),
    ("Internet subscription", "Bills & Utilities", "Internet"),
    ("internet payment", "Bills & Utilities", "Internet"),
    ("internet bill", "Bills & Utilities", "Internet"),
    ("broadband payment", "Bills & Utilities", "Internet"),
    ("utility bill internet", "Bills & Utilities", "Internet"),
    ("bayad internet", "Bills & Utilities", "Internet"),
    ("quarterly internet payment", "Bills & Utilities", "Internet"),
    ("monthly internet plan", "Bills & Utilities", "Internet"),
    
    ("tubig bill", "Bills & Utilities", "Water"),
    ("water bill payment", "Bills & Utilities", "Water"),
    ("monthly water utilities", "Bills & Utilities", "Water"),
    ("bayad tubig", "Bills & Utilities", "Water"),
    ("bill ng tubig", "Bills & Utilities", "Water"),
    ("water meter charge", "Bills & Utilities", "Water"),
    ("water service fee", "Bills & Utilities", "Water"),
    ("water utility bill", "Bills & Utilities", "Water"),
    ("water bill", "Bills & Utilities", "Water"),
    ("quarterly water payment", "Bills & Utilities", "Water"),
    ("water consumption charge", "Bills & Utilities", "Water"),
    ("tubig na bayarin", "Bills & Utilities", "Water"),
    ("metro ng tubig", "Bills & Utilities", "Water"),
    ("singil sa tubig", "Bills & Utilities", "Water"),
    ("water district payment", "Bills & Utilities", "Water"),
    ("water supply bill", "Bills & Utilities", "Water"),
    ("patubig bayarin", "Bills & Utilities", "Water"),
    ("konsumo ng tubig", "Bills & Utilities", "Water"),

    ("PLDT Home Fiber monthly", "Bills & Utilities", "Internet"),
    ("Globe At Home internet", "Bills & Utilities", "Internet"),
    ("Converge ICT payment", "Bills & Utilities", "Internet"),
    ("internet monthly bill", "Bills & Utilities", "Internet"),
    ("wifi service payment", "Bills & Utilities", "Internet"),
    ("broadband payment", "Bills & Utilities", "Internet"),
    ("bayad internet", "Bills & Utilities", "Internet"),
    ("wifi bill", "Bills & Utilities", "Internet"),
    ("load sa wifi", "Bills & Utilities", "Internet"),
    ("fiber optic connection", "Bills & Utilities", "Internet"),
    ("Sky Fiber payment", "Bills & Utilities", "Internet"),
    ("DITO Home internet", "Bills & Utilities", "Internet"),
    ("fixed broadband service", "Bills & Utilities", "Internet"),
    ("home network subscription", "Bills & Utilities", "Internet"),
    ("internet provider bill", "Bills & Utilities", "Internet"),
    ("bayad sa koneksyon", "Bills & Utilities", "Internet"),
    ("singil sa internet", "Bills & Utilities", "Internet"),
    ("bayad sa wifi", "Bills & Utilities", "Internet"),
    ("internet sa bahay", "Bills & Utilities", "Internet"),
    ("fiber connection bayarin", "Bills & Utilities", "Internet"),

    ("Globe postpaid plan", "Bills & Utilities", "Phone Plan"),
    ("Smart postpaid bill", "Bills & Utilities", "Phone Plan"),
    ("prepaid load Globe", "Bills & Utilities", "Phone Plan"),
    ("Smart regular load", "Bills & Utilities", "Phone Plan"),
    ("TnT load", "Bills & Utilities", "Phone Plan"),
    ("mobile plan monthly", "Bills & Utilities", "Phone Plan"),
    ("phone bill payment", "Bills & Utilities", "Phone Plan"),
    ("bayad telepono", "Bills & Utilities", "Phone Plan"),
    ("load sa phone", "Bills & Utilities", "Phone Plan"),
    ("Gomo load", "Bills & Utilities", "Phone Plan"),
    ("Dito load", "Bills & Utilities", "Phone Plan"),
    ("Talk load", "Bills & Utilities", "Phone Plan"),
    ("TNT load", "Bills & Utilities", "Phone Plan"),
    ("Talk N Text load", "Bills & Utilities", "Phone Plan"),
    ("Sun Cellular load", "Bills & Utilities", "Phone Plan"),
    ("Sun load", "Bills & Utilities", "Phone Plan"),
    ("TM load", "Bills & Utilities", "Phone Plan"),
    ("mobile data package", "Bills & Utilities", "Phone Plan"),
    ("cellphone plan renewal", "Bills & Utilities", "Phone Plan"),
    ("postpaid line payment", "Bills & Utilities", "Phone Plan"),
    ("data bundle purchase", "Bills & Utilities", "Phone Plan"),
    ("cell service bill", "Bills & Utilities", "Phone Plan"),
    ("telepono bill", "Bills & Utilities", "Phone Plan"),
    ("load para sa selpon", "Bills & Utilities", "Phone Plan"),
    ("data promo avail", "Bills & Utilities", "Phone Plan"),
    ("call and text package", "Bills & Utilities", "Phone Plan"),
    ("pang-load sa cellphone", "Bills & Utilities", "Phone Plan"),
    ("data allocation purchase", "Bills & Utilities", "Phone Plan"),
    ("text promo avail", "Bills & Utilities", "Phone Plan"),
    ("call promo subscription", "Bills & Utilities", "Phone Plan"),

    ("Netflix subscription", "Bills & Utilities", "Streaming Services"),
    ("Spotify Premium", "Bills & Utilities", "Streaming Services"),
    ("Disney+ subscription", "Bills & Utilities", "Streaming Services"),
    ("Amazon Prime", "Bills & Utilities", "Streaming Services"),
    ("HBO Go monthly", "Bills & Utilities", "Streaming Services"),
    ("Viu Premium", "Bills & Utilities", "Streaming Services"),
    ("YouTube Premium", "Bills & Utilities", "Streaming Services"),
    ("Apple Music subscription", "Bills & Utilities", "Streaming Services"),
    ("WeTV subscription", "Bills & Utilities", "Streaming Services"),
    ("iQiyi monthly", "Bills & Utilities", "Streaming Services"),
    ("streaming service monthly", "Bills & Utilities", "Streaming Services"),
    ("video streaming subscription", "Bills & Utilities", "Streaming Services"),
    ("music subscription", "Bills & Utilities", "Streaming Services"),
    ("bayad Netflix", "Bills & Utilities", "Streaming Services"),
    ("bayad Spotify premium", "Bills & Utilities", "Streaming Services"),
    ("bayad Disney+", "Bills & Utilities", "Streaming Services"),
    ("bayad Amazon Prime", "Bills & Utilities", "Streaming Services"),
    ("bayad HBO Go", "Bills & Utilities", "Streaming Services"),
    ("bayad Viu Premium", "Bills & Utilities", "Streaming Services"),
    ("bayad YouTube Premium", "Bills & Utilities", "Streaming Services"),
    ("bayad Apple Music", "Bills & Utilities", "Streaming Services"),
    ("bayad WeTV", "Bills & Utilities", "Streaming Services"),
    ("bayad iQiyi", "Bills & Utilities", "Streaming Services"),
    ("bayad streaming service", "Bills & Utilities", "Streaming Services"),
    ("bayad video streaming", "Bills & Utilities", "Streaming Services"),
    ("bayad music subscription", "Bills & Utilities", "Streaming Services"),
    ("Netflix annual plan", "Bills & Utilities", "Streaming Services"),
    ("Crunchyroll subscription", "Bills & Utilities", "Streaming Services"),
    ("Tidal music service", "Bills & Utilities", "Streaming Services"),
    ("Discovery+ monthly", "Bills & Utilities", "Streaming Services"),
    ("Twitch subscription", "Bills & Utilities", "Streaming Services"),
    ("Prime Video membership", "Bills & Utilities", "Streaming Services"),
    ("Apple TV+ service", "Bills & Utilities", "Streaming Services"),
    ("suskrisyon sa Netflix", "Bills & Utilities", "Streaming Services"),
    ("bayad sa online movies", "Bills & Utilities", "Streaming Services"),
    ("serbisyo ng streaming", "Bills & Utilities", "Streaming Services"),
    ("bayad para sa musika", "Bills & Utilities", "Streaming Services"),
    ("Netflix family plan", "Bills & Utilities", "Streaming Services"),
    ("Deezer Premium", "Bills & Utilities", "Streaming Services"),
    ("bayad sa Crunchyroll", "Bills & Utilities", "Streaming Services"),

    ("Monthly rent BGC condo", "Bills & Utilities", "Rent/Mortgage"),
    ("House rental Quezon City", "Bills & Utilities", "Rent/Mortgage"),
    ("Condo association dues", "Bills & Utilities", "Rent/Mortgage"),
    ("rent payment apartment", "Bills & Utilities", "Rent/Mortgage"),
    ("house amortization", "Bills & Utilities", "Rent/Mortgage"),
    ("pag-ibig housing loan", "Bills & Utilities", "Rent/Mortgage"),
    ("monthly association dues", "Bills & Utilities", "Rent/Mortgage"),
    ("annual condo dues", "Bills & Utilities", "Rent/Mortgage"),
    ("renta bahay", "Bills & Utilities", "Rent/Mortgage"),
    ("upa ng apartment", "Bills & Utilities", "Rent/Mortgage"),
    ("monthly apartment rent", "Bills & Utilities", "Rent/Mortgage"),
    ("house payment", "Bills & Utilities", "Rent/Mortgage"),
    ("monthly mortgage", "Bills & Utilities", "Rent/Mortgage"),
    ("monthly rent", "Bills & Utilities", "Rent/Mortgage"),
    ("condo", "Bills & Utilities", "Rent/Mortgage"),
    ("renta", "Bills & Utilities", "Rent/Mortgage"),
    ("upahan", "Bills & Utilities", "Rent/Mortgage"),
    ("bahay", "Bills & Utilities", "Rent/Mortgage"),
    ("apartment", "Bills & Utilities", "Rent/Mortgage"),
    ("renta ng bahay", "Bills & Utilities", "Rent/Mortgage"),
    ("upa ng bahay", "Bills & Utilities", "Rent/Mortgage"),
    ("condominium", "Bills & Utilities", "Rent/Mortgage"),
    ("townhouse rental fee", "Bills & Utilities", "Rent/Mortgage"),
    ("studio apartment rent", "Bills & Utilities", "Rent/Mortgage"),
    ("dormitory payment", "Bills & Utilities", "Rent/Mortgage"),
    ("boarding house fee", "Bills & Utilities", "Rent/Mortgage"),
    ("lease agreement payment", "Bills & Utilities", "Rent/Mortgage"),
    ("property rental", "Bills & Utilities", "Rent/Mortgage"),
    ("amilyar sa bahay", "Bills & Utilities", "Rent/Mortgage"),
    ("bayad sa tirahan", "Bills & Utilities", "Rent/Mortgage"),
    ("hulog sa bahay loan", "Bills & Utilities", "Rent/Mortgage"),
    ("bayad sa titirhan", "Bills & Utilities", "Rent/Mortgage"),
    ("apartment rental monthly", "Bills & Utilities", "Rent/Mortgage"),
    ("boarding house payment", "Bills & Utilities", "Rent/Mortgage"),
    ("bedspace rental", "Bills & Utilities", "Rent/Mortgage"),
    ("dormitory monthly fee", "Bills & Utilities", "Rent/Mortgage"),

    ("cooking gas refill", "Bills & Utilities", "Gas"),
    ("gas utility bill", "Bills & Utilities", "Gas"),
    ("Petron gas tank refill", "Bills & Utilities", "Gas"),
    ("Shell gas for stove", "Bills & Utilities", "Gas"),
    ("LPG gas delivery", "Bills & Utilities", "Gas"),
    ("bayad gas", "Bills & Utilities", "Gas"),
    ("tangke ng gas", "Bills & Utilities", "Gas"),
    ("gasul", "Bills & Utilities", "Gas"),
    ("LPG", "Bills & Utilities", "Gas"),
    ("gasolina", "Bills & Utilities", "Gas"),
    ("gasul delivery", "Bills & Utilities", "Gas"),
    ("gasul refill", "Bills & Utilities", "Gas"),
    ("gasul tank", "Bills & Utilities", "Gas"),
    ("gasul stove", "Bills & Utilities", "Gas"),
    ("gasul tank refill", "Bills & Utilities", "Gas"),
    ("gasul delivery", "Bills & Utilities", "Gas"),
    ("gasul refill", "Bills & Utilities", "Gas"),
    ("gasul tank", "Bills & Utilities", "Gas"),
    ("gasul stove", "Bills & Utilities", "Gas"),
    ("gasul tank refill", "Bills & Utilities", "Gas"),
    ("propane tank delivery", "Bills & Utilities", "Gas"),
    ("natural gas bill payment", "Bills & Utilities", "Gas"),
    ("cooking fuel purchase", "Bills & Utilities", "Gas"),
    ("kitchen gas cylinder", "Bills & Utilities", "Gas"),
    ("gas for cooking", "Bills & Utilities", "Gas"),
    ("Solane gas tank", "Bills & Utilities", "Gas"),
    ("pambahay na gas", "Bills & Utilities", "Gas"),
    ("pampakulay na gas", "Bills & Utilities", "Gas"),
    ("pang-luto na gas", "Bills & Utilities", "Gas"),
    ("refill ng pangkusina", "Bills & Utilities", "Gas"),
    ("gas para sa kalan", "Bills & Utilities", "Gas"),
    ("tangke para sa kusina", "Bills & Utilities", "Gas"),
    ("LPG delivery service", "Bills & Utilities", "Gas"),
    ("butane canister purchase", "Bills & Utilities", "Gas"),

    # Food & Groceries entries
    ("SM Supermarket grocery", "Food & Groceries", "Groceries"),
    ("Puregold weekly groceries", "Food & Groceries", "Groceries"),
    ("Robinson's Supermarket", "Food & Groceries", "Groceries"),
    ("Marketplace by Rustan's", "Food & Groceries", "Groceries"),
    ("Landers shopping", "Food & Groceries", "Groceries"),
    ("S&R grocery shopping", "Food & Groceries", "Groceries"),
    ("MetroMart groceries delivery", "Food & Groceries", "Groceries"),
    ("palengke groceries", "Food & Groceries", "Groceries"),
    ("wet market", "Food & Groceries", "Groceries"),
    ("sari-sari store", "Food & Groceries", "Groceries"),
    ("7-Eleven snacks", "Food & Groceries", "Groceries"),
    ("supermarket shopping", "Food & Groceries", "Groceries"),
    ("weekly grocery run", "Food & Groceries", "Groceries"),
    ("food supplies", "Food & Groceries", "Groceries"),
    ("fresh produce", "Food & Groceries", "Groceries"),
    ("meat and poultry", "Food & Groceries", "Groceries"),
    ("pamibili sa palengke", "Food & Groceries", "Groceries"),
    ("grocery sa supermarket", "Food & Groceries", "Groceries"),
    ("mga bigas", "Food & Groceries", "Groceries"),
    ("ulam", "Food & Groceries", "Groceries"),
    ("pagkain", "Food & Groceries", "Groceries"),
    ("gulay", "Food & Groceries", "Groceries"),
    ("karne", "Food & Groceries", "Groceries"),
    ("prutas", "Food & Groceries", "Groceries"),
    ("paninda", "Food & Groceries", "Groceries"),
    ("pagkain sa bahay", "Food & Groceries", "Groceries"),
    ("pagkain sa tindahan", "Food & Groceries", "Groceries"),
    ("pagkain sa palengke", "Food & Groceries", "Groceries"),
    ("pagkain sa supermarket", "Food & Groceries", "Groceries"),
    ("Walter Mart groceries", "Food & Groceries", "Groceries"),
    ("All Day Supermarket", "Food & Groceries", "Groceries"),
    ("Savemore shopping", "Food & Groceries", "Groceries"),
    ("Shopwise bulk buying", "Food & Groceries", "Groceries"),
    ("monthly pantry restocking", "Food & Groceries", "Groceries"),
    ("canned goods purchase", "Food & Groceries", "Groceries"),
    ("seafood section", "Food & Groceries", "Groceries"),
    ("bakery items", "Food & Groceries", "Groceries"),
    ("frozen foods stock", "Food & Groceries", "Groceries"),
    ("dairy products", "Food & Groceries", "Groceries"),
    ("grocery delivery service", "Food & Groceries", "Groceries"),
    ("bilihan ng pagkain", "Food & Groceries", "Groceries"),
    ("tindang gulay", "Food & Groceries", "Groceries"),
    ("mamili ng ulam", "Food & Groceries", "Groceries"),
    ("isda at hipon", "Food & Groceries", "Groceries"),
    ("presyong bilihin", "Food & Groceries", "Groceries"),
    ("grocery sa talipapa", "Food & Groceries", "Groceries"),
    ("de lata na pagkain", "Food & Groceries", "Groceries"),
    ("karne at manok", "Food & Groceries", "Groceries"),
    ("pamilihan ng pagkain", "Food & Groceries", "Groceries"),
    ("grocery shopping online", "Food & Groceries", "Groceries"),

    ("Jollibee lunch", "Food & Groceries", "Dining Out"),
    ("McDonald's breakfast", "Food & Groceries", "Dining Out"),
    ("KFC dinner", "Food & Groceries", "Dining Out"),
    ("Chowking merienda", "Food & Groceries", "Dining Out"),
    ("Max's Restaurant", "Food & Groceries", "Dining Out"),
    ("Ministop food", "Food & Groceries", "Dining Out"),
    ("Uncle John's food", "Food & Groceries", "Dining Out"),
    ("Mang Inasal", "Food & Groceries", "Dining Out"),
    ("Goldilocks", "Food & Groceries", "Dining Out"),
    ("Greenwich pizza", "Food & Groceries", "Dining Out"),
    ("breakfast meal", "Food & Groceries", "Dining Out"),
    ("lunch restaurant", "Food & Groceries", "Dining Out"),
    ("dinner out", "Food & Groceries", "Dining Out"),
    ("afternoon snack", "Food & Groceries", "Dining Out"),
    ("almusal sa labas", "Food & Groceries", "Dining Out"),
    ("tanghalian", "Food & Groceries", "Dining Out"),
    ("hapunan sa labas", "Food & Groceries", "Dining Out"),
    ("meryenda", "Food & Groceries", "Dining Out"),
    ("kainan sa labas", "Food & Groceries", "Dining Out"),
    ("Shakey's pizza", "Food & Groceries", "Dining Out"),
    ("Yellow Cab dinner", "Food & Groceries", "Dining Out"),
    ("Burger King meal", "Food & Groceries", "Dining Out"),
    ("Tokyo Tokyo lunch", "Food & Groceries", "Dining Out"),
    ("Pancake House breakfast", "Food & Groceries", "Dining Out"),
    ("Aristocrat restaurant", "Food & Groceries", "Dining Out"),
    ("Wendy's burger", "Food & Groceries", "Dining Out"),
    ("Army Navy burrito", "Food & Groceries", "Dining Out"),
    ("food court meal", "Food & Groceries", "Dining Out"),
    ("samgyupsal dinner", "Food & Groceries", "Dining Out"),
    ("buffet restaurant", "Food & Groceries", "Dining Out"),
    ("fast food takeout", "Food & Groceries", "Dining Out"),
    ("family restaurant", "Food & Groceries", "Dining Out"),
    ("tusok-tusok sa daan", "Food & Groceries", "Dining Out"),
    ("karinderya ulam", "Food & Groceries", "Dining Out"),
    ("tapsihan breakfast", "Food & Groceries", "Dining Out"),
    ("silog meal", "Food & Groceries", "Dining Out"),
    ("palabok sa labas", "Food & Groceries", "Dining Out"),
    ("bilihan ng ulam", "Food & Groceries", "Dining Out"),
    ("drive-thru order", "Food & Groceries", "Dining Out"),
    ("casual dining", "Food & Groceries", "Dining Out"),

    ("Starbucks coffee", "Food & Groceries", "Coffee/Beverages"),
    ("CBTL drinks", "Food & Groceries", "Coffee/Beverages"),
    ("Tim Hortons coffee", "Food & Groceries", "Coffee/Beverages"),
    ("Dunkin Donuts", "Food & Groceries", "Coffee/Beverages"),
    ("Ministop coffee", "Food & Groceries", "Coffee/Beverages"),
    ("Uncle John's coffee", "Food & Groceries", "Coffee/Beverages"),
    ("coffee shop", "Food & Groceries", "Coffee/Beverages"),
    ("milk tea", "Food & Groceries", "Coffee/Beverages"),
    ("bubble tea", "Food & Groceries", "Coffee/Beverages"),
    ("kape sa labas", "Food & Groceries", "Coffee/Beverages"),
    ("milk tea shop", "Food & Groceries", "Coffee/Beverages"),
    ("bubble tea shop", "Food & Groceries", "Coffee/Beverages"),
    ("kape", "Food & Groceries", "Coffee/Beverages"),
    ("milk tea", "Food & Groceries", "Coffee/Beverages"),
    ("cafe", "Food & Groceries", "Coffee/Beverages"),
    ("Seattle's Best Coffee", "Food & Groceries", "Coffee/Beverages"),
    ("Bo's Coffee purchase", "Food & Groceries", "Coffee/Beverages"),
    ("Figaro coffee shop", "Food & Groceries", "Coffee/Beverages"),
    ("Chatime milk tea", "Food & Groceries", "Coffee/Beverages"),
    ("Gong Cha pearls", "Food & Groceries", "Coffee/Beverages"),
    ("Serenitea order", "Food & Groceries", "Coffee/Beverages"),
    ("Tiger Sugar", "Food & Groceries", "Coffee/Beverages"),
    ("7-Eleven coffee", "Food & Groceries", "Coffee/Beverages"),
    ("iced coffee takeaway", "Food & Groceries", "Coffee/Beverages"),
    ("fresh fruit juice", "Food & Groceries", "Coffee/Beverages"),
    ("smoothie drink", "Food & Groceries", "Coffee/Beverages"),
    ("hot chocolate", "Food & Groceries", "Coffee/Beverages"),
    ("frappe drink", "Food & Groceries", "Coffee/Beverages"),
    ("tsaa sa labas", "Food & Groceries", "Coffee/Beverages"),
    ("inuming sago", "Food & Groceries", "Coffee/Beverages"),
    ("strawberry shake", "Food & Groceries", "Coffee/Beverages"),
    ("barako coffee", "Food & Groceries", "Coffee/Beverages"),
    ("kapeng mainit", "Food & Groceries", "Coffee/Beverages"),
    ("inuming may yelo", "Food & Groceries", "Coffee/Beverages"),
    ("fruit tea order", "Food & Groceries", "Coffee/Beverages"),
    ("espresso shot", "Food & Groceries", "Coffee/Beverages"),
    ("americano coffee", "Food & Groceries", "Coffee/Beverages"),
    ("mocha latte", "Food & Groceries", "Coffee/Beverages"),
    ("caramel macchiato", "Food & Groceries", "Coffee/Beverages"),

    ("GrabFood delivery", "Food & Groceries", "Food Delivery"),
    ("Foodpanda order", "Food & Groceries", "Food Delivery"),
    ("Pick.A.Roo food delivery", "Food & Groceries", "Food Delivery"),
    ("Yellow Cab delivery", "Food & Groceries", "Food Delivery"),
    ("Angel's Pizza", "Food & Groceries", "Food Delivery"),
    ("food delivery order", "Food & Groceries", "Food Delivery"),
    ("online food order", "Food & Groceries", "Food Delivery"),
    ("meal delivery", "Food & Groceries", "Food Delivery"),
    ("delivery ng pagkain", "Food & Groceries", "Food Delivery"),
    ("padeliver na food", "Food & Groceries", "Food Delivery"),
    ("order sa foodpanda", "Food & Groceries", "Food Delivery"),
    ("order sa grabfood", "Food & Groceries", "Food Delivery"),
    ("order sa pickaroo", "Food & Groceries", "Food Delivery"),
    ("order sa delivery", "Food & Groceries", "Food Delivery"),
    ("order sa food delivery", "Food & Groceries", "Food Delivery"),
    ("order sa online food", "Food & Groceries", "Food Delivery"),
    ("order sa meal delivery", "Food & Groceries", "Food Delivery"),
    ("order sa pagkain", "Food & Groceries", "Food Delivery"),
    ("order sa delivery ng pagkain", "Food & Groceries", "Food Delivery"),
    ("Jollibee delivery app", "Food & Groceries", "Food Delivery"),
    ("McDelivery service", "Food & Groceries", "Food Delivery"),
    ("Greenwich delivery order", "Food & Groceries", "Food Delivery"),
    ("Shakey's delivery", "Food & Groceries", "Food Delivery"),
    ("Chowking delivery", "Food & Groceries", "Food Delivery"),
    ("KFC delivery website", "Food & Groceries", "Food Delivery"),
    ("Max's delivery service", "Food & Groceries", "Food Delivery"),
    ("Pizza Hut delivery", "Food & Groceries", "Food Delivery"),
    ("food delivery app fee", "Food & Groceries", "Food Delivery"),
    ("restaurant delivery charge", "Food & Groceries", "Food Delivery"),
    ("online food platform", "Food & Groceries", "Food Delivery"),
    ("pagkain sa delivery app", "Food & Groceries", "Food Delivery"),
    ("order ng pagkain online", "Food & Groceries", "Food Delivery"),
    ("delivery rider tip", "Food & Groceries", "Food Delivery"),
    ("food delivery service", "Food & Groceries", "Food Delivery"),
    ("take-out food order", "Food & Groceries", "Food Delivery"),
    ("padala ng pagkain", "Food & Groceries", "Food Delivery"),
    ("hatid na pagkain", "Food & Groceries", "Food Delivery"),
    ("online food platform", "Food & Groceries", "Food Delivery"),
    ("delivery app subscription", "Food & Groceries", "Food Delivery"),
    ("food ordering platform", "Food & Groceries", "Food Delivery"),

    # Transportation entries
    ("Grab car to work", "Transportation", "Public Transit"),
    ("Angkas ride", "Transportation", "Public Transit"),
    ("JoyRide booking", "Transportation", "Public Transit"),
    ("Beep card load", "Transportation", "Public Transit"),
    ("MRT fare", "Transportation", "Public Transit"),
    ("LRT ticket", "Transportation", "Public Transit"),
    ("P2P bus fare", "Transportation", "Public Transit"),
    ("UV Express fare", "Transportation", "Public Transit"),
    ("jeepney fare", "Transportation", "Public Transit"),
    ("tricycle fare", "Transportation", "Public Transit"),
    ("ride hailing service", "Transportation", "Public Transit"),
    ("bus fare", "Transportation", "Public Transit"),
    ("train ticket", "Transportation", "Public Transit"),
    ("taxi fare", "Transportation", "Public Transit"),
    ("motorcycle taxi", "Transportation", "Public Transit"),
    ("pamasahe", "Transportation", "Public Transit"),
    ("sa bus", "Transportation", "Public Transit"),
    ("sa jeep", "Transportation", "Public Transit"),
    ("sa trike", "Transportation", "Public Transit"),
    ("transpo", "Transportation", "Public Transit"),
    ("LRT single journey", "Transportation", "Public Transit"),
    ("MRT stored value ticket", "Transportation", "Public Transit"),
    ("BGC bus ride", "Transportation", "Public Transit"),
    ("PNR train fare", "Transportation", "Public Transit"),
    ("Citylink bus fare", "Transportation", "Public Transit"),
    ("EDSA Carousel ride", "Transportation", "Public Transit"),
    ("Grab car booking fee", "Transportation", "Public Transit"),
    ("provincial bus ticket", "Transportation", "Public Transit"),
    ("ferry boat passage", "Transportation", "Public Transit"),
    ("modern jeepney ride", "Transportation", "Public Transit"),
    ("shuttle service payment", "Transportation", "Public Transit"),
    ("office transportation allowance", "Transportation", "Public Transit"),
    ("carpool contribution", "Transportation", "Public Transit"),
    ("pangulong dyip", "Transportation", "Public Transit"),
    ("sakay ng bus", "Transportation", "Public Transit"),
    ("bayad sa dyip", "Transportation", "Public Transit"),
    ("pamasahe sa tren", "Transportation", "Public Transit"),
    ("sakay ng barko", "Transportation", "Public Transit"),
    ("biyahe sa bus", "Transportation", "Public Transit"),
    ("pamasahe sa modern jeep", "Transportation", "Public Transit"),
    ("commute expense", "Transportation", "Public Transit"),
    ("airport transfer service", "Transportation", "Public Transit"),
    ("sakay sa pampublikong sasakyan", "Transportation", "Public Transit"),

    ("Shell gas station", "Transportation", "Fuel/Gas"),
    ("Petron fuel", "Transportation", "Fuel/Gas"),
    ("Caltex gas", "Transportation", "Fuel/Gas"),
    ("fuel purchase", "Transportation", "Fuel/Gas"),
    ("gasoline refill", "Transportation", "Fuel/Gas"),
    ("diesel fuel", "Transportation", "Fuel/Gas"),
    ("gasolina", "Transportation", "Fuel/Gas"),
    ("krudo", "Transportation", "Fuel/Gas"),
    ("diesel", "Transportation", "Fuel/Gas"),
    ("unleaded", "Transportation", "Fuel/Gas"),
    ("unleaded gas", "Transportation", "Fuel/Gas"),
    ("Phoenix gas station", "Transportation", "Fuel/Gas"),
    ("Seaoil fuel purchase", "Transportation", "Fuel/Gas"),
    ("Total gas station", "Transportation", "Fuel/Gas"),
    ("Cleanfuel refill", "Transportation", "Fuel/Gas"),
    ("Unioil gasoline", "Transportation", "Fuel/Gas"),
    ("premium gasoline", "Transportation", "Fuel/Gas"),
    ("regular gas", "Transportation", "Fuel/Gas"),
    ("full tank refill", "Transportation", "Fuel/Gas"),
    ("gas station fill up", "Transportation", "Fuel/Gas"),
    ("motorcycle fuel", "Transportation", "Fuel/Gas"),
    ("car petrol", "Transportation", "Fuel/Gas"),
    ("auto gas", "Transportation", "Fuel/Gas"),
    ("gasolinahan", "Transportation", "Fuel/Gas"),
    ("paglagay ng gas", "Transportation", "Fuel/Gas"),
    ("puno tangke", "Transportation", "Fuel/Gas"),
    ("gasoline para sa motor", "Transportation", "Fuel/Gas"),
    ("isang litro ng krudo", "Transportation", "Fuel/Gas"),
    ("gas sa kotse", "Transportation", "Fuel/Gas"),
    ("gasoline allowance", "Transportation", "Fuel/Gas"),
    ("weekly fuel budget", "Transportation", "Fuel/Gas"),

    ("Car change oil", "Transportation", "Vehicle Maintenance"),
    ("Tire replacement", "Transportation", "Vehicle Maintenance"),
    ("Car wash", "Transportation", "Vehicle Maintenance"),
    ("parking fee", "Transportation", "Vehicle Maintenance"),
    ("car registration", "Transportation", "Vehicle Maintenance"),
    ("LTO renewal", "Transportation", "Vehicle Maintenance"),
    ("car battery", "Transportation", "Vehicle Maintenance"),
    ("vehicle maintenance", "Transportation", "Vehicle Maintenance"),
    ("car service", "Transportation", "Vehicle Maintenance"),
    ("vehicle repair", "Transportation", "Vehicle Maintenance"),
    ("change oil", "Transportation", "Vehicle Maintenance"),
    ("talyer", "Transportation", "Vehicle Maintenance"),
    ("mekaniko", "Transportation", "Vehicle Maintenance"),
    ("parking", "Transportation", "Vehicle Maintenance"),
    ("renewal ng sasakyan", "Transportation", "Vehicle Maintenance"),
    ("car tune up service", "Transportation", "Vehicle Maintenance"),
    ("wheel alignment", "Transportation", "Vehicle Maintenance"),
    ("brake pad replacement", "Transportation", "Vehicle Maintenance"),
    ("car air conditioning repair", "Transportation", "Vehicle Maintenance"),
    ("car engine overhaul", "Transportation", "Vehicle Maintenance"),
    ("car accessories", "Transportation", "Vehicle Maintenance"),
    ("car window tinting", "Transportation", "Vehicle Maintenance"),
    ("car detailing service", "Transportation", "Vehicle Maintenance"),
    ("emission testing fee", "Transportation", "Vehicle Maintenance"),
    ("car battery replacement", "Transportation", "Vehicle Maintenance"),
    ("car maintenance checkup", "Transportation", "Vehicle Maintenance"),
    ("transmission fluid change", "Transportation", "Vehicle Maintenance"),
    ("car diagnostic scan", "Transportation", "Vehicle Maintenance"),
    ("pagpapaayos ng kotse", "Transportation", "Vehicle Maintenance"),
    ("pagpalit ng gulong", "Transportation", "Vehicle Maintenance"),
    ("talyer service", "Transportation", "Vehicle Maintenance"),
    ("langis ng sasakyan", "Transportation", "Vehicle Maintenance"),
    ("car seat repair", "Transportation", "Vehicle Maintenance"),
    ("car paint job", "Transportation", "Vehicle Maintenance"),
    ("car window repair", "Transportation", "Vehicle Maintenance"),
    ("car suspension fix", "Transportation", "Vehicle Maintenance"),
    ("pagpapakinis ng sasakyan", "Transportation", "Vehicle Maintenance"),
    ("pagpapa-aircon ng kotse", "Transportation", "Vehicle Maintenance"),
    ("sasakyan maintenance", "Transportation", "Vehicle Maintenance"),
    ("annual car maintenance", "Transportation", "Vehicle Maintenance"),

    ("Car insurance monthly", "Insurance", "Car Insurance"),
    ("car insurance", "Insurance", "Car Insurance"),
    ("auto insurance", "Insurance", "Car Insurance"),
    ("vehicle insurance premium", "Insurance", "Car Insurance"),
    ("comprehensive car insurance", "Insurance", "Car Insurance"),
    ("third party car insurance", "Insurance", "Car Insurance"),
    ("CTPL insurance renewal", "Insurance", "Car Insurance"),
    ("auto policy premium", "Insurance", "Car Insurance"),
    ("car insurance renewal", "Insurance", "Car Insurance"),
    ("vehicle liability coverage", "Insurance", "Car Insurance"),
    ("motor insurance", "Insurance", "Car Insurance"),
    ("car policy payment", "Insurance", "Car Insurance"),
    ("seguro ng kotse", "Insurance", "Car Insurance"),
    ("car protection plan", "Insurance", "Car Insurance"),
    ("annual vehicle insurance", "Insurance", "Car Insurance"),
    ("motor vehicle policy", "Insurance", "Car Insurance"),
    ("car damage protection", "Insurance", "Car Insurance"),

    # Home Maintenance (expanded)
    ("Hardware store supplies", "Home Maintenance", "Home Improvements"),
    ("Paint and painting supplies", "Home Maintenance", "Home Improvements"),
    ("Home depot purchase", "Home Maintenance", "Home Improvements"),
    ("Home renovation material", "Home Maintenance", "Home Improvements"),
    ("Garden maintenance tools", "Home Maintenance", "Home Improvements"),
    ("Home security system", "Home Maintenance", "Home Improvements"),
    ("painting supplies", "Home Maintenance", "Home Improvements"),
    ("home renovation", "Home Maintenance", "Home Improvements"),
    ("garden tools", "Home Maintenance", "Home Improvements"),
    ("home security", "Home Maintenance", "Home Improvements"),
    ("home improvement", "Home Maintenance", "Home Improvements"),
    ("home maintenance", "Home Maintenance", "Home Improvements"),
    ("house renovation", "Home Maintenance", "Home Improvements"),
    ("house painting", "Home Maintenance", "Home Improvements"),
    ("house maintenance", "Home Maintenance", "Home Improvements"),
    ("bahay at lupa", "Home Maintenance", "Home Improvements"),
    ("kagamitan sa bahay", "Home Maintenance", "Home Improvements"),
    ("pintura", "Home Maintenance", "Home Improvements"),
    ("kagamitan sa hardin", "Home Maintenance", "Home Improvements"),
    ("kagamitan sa kusina", "Home Maintenance", "Home Improvements"),
    ("kagamitan sa banyo", "Home Maintenance", "Home Improvements"),
    ("kagamitan sa sala", "Home Maintenance", "Home Improvements"),
    ("kagamitan sa kwarto", "Home Maintenance", "Home Improvements"),
    ("kagamitan sa labas", "Home Maintenance", "Home Improvements"),
    ("kagamitan sa loob", "Home Maintenance", "Home Improvements"),
    ("kagamitan sa labas", "Home Maintenance", "Home Improvements"),
    ("kagamitan sa bahay", "Home Maintenance", "Home Improvements"),
    ("kagamitan sa kusina", "Home Maintenance", "Home Improvements"),
    ("kagamitan sa banyo", "Home Maintenance", "Home Improvements"),
    ("kagamitan sa sala", "Home Maintenance", "Home Improvements"),

    ("Electrical repair materials", "Home Maintenance", "Repairs"),
    ("Plumbing repair kit", "Home Maintenance", "Repairs"),
    ("Furniture repair kit", "Home Maintenance", "Repairs"),
    ("Aircon cleaning service", "Home Maintenance", "Repairs"),
    ("Pest control service", "Home Maintenance", "Repairs"),
    ("Window repair", "Home Maintenance", "Repairs"),
    ("Roof repair materials", "Home Maintenance", "Repairs"),
    ("kabayo ng bahay", "Home Maintenance", "Repairs"),
    ("gamit sa pagkumpuni", "Home Maintenance", "Repairs"),
    ("repairs sa bahay", "Home Maintenance", "Repairs"),
    ("furniture repair", "Home Maintenance", "Repairs"),
    ("pest control", "Home Maintenance", "Repairs"),
    ("window replacement", "Home Maintenance", "Repairs"),
    ("roof repair", "Home Maintenance", "Repairs"),
    ("house repair", "Home Maintenance", "Repairs"),
    ("pagkukumpuni", "Home Maintenance", "Repairs"),
    ("Floor maintenance supplies", "Home Maintenance", "Cleaning Supplies"),
    ("floor cleaning", "Home Maintenance", "Cleaning Supplies"),
    ("house cleaning", "Home Maintenance", "Cleaning Supplies"),
    ("cleaning materials", "Home Maintenance", "Cleaning Supplies"),
    ("cleaning supplies", "Home Maintenance", "Cleaning Supplies"),
    ("cleaning tools", "Home Maintenance", "Cleaning Supplies"),
    ("cleaning equipment", "Home Maintenance", "Cleaning Supplies"),
    ("cleaning products", "Home Maintenance", "Cleaning Supplies"),
    ("cleaning chemicals", "Home Maintenance", "Cleaning Supplies"),
    ("cleaning agents", "Home Maintenance", "Cleaning Supplies"),
    ("cleaning solutions", "Home Maintenance", "Cleaning Supplies"),
    ("walis tambo", "Home Maintenance", "Cleaning Supplies"),
    ("walis tingting", "Home Maintenance", "Cleaning Supplies"),
    ("basahan", "Home Maintenance", "Cleaning Supplies"),


    # Healthcare entries
    ("Mercury Drug medicines", "Healthcare", "Medications"),
    ("Watsons pharmacy", "Healthcare", "Medications"),
    ("South Star Drug purchase", "Healthcare", "Medications"),
    ("The Generics Pharmacy", "Healthcare", "Medications"),
    ("Rose Pharmacy", "Healthcare", "Medications"),
    ("medicine purchase", "Healthcare", "Medications"),
    ("prescription drugs", "Healthcare", "Medications"),
    ("over the counter medicine", "Healthcare", "Medications"),
    ("gamot", "Healthcare", "Medications"),
    ("medisina", "Healthcare", "Medications"),
    ("reseta", "Healthcare", "Medications"),
    ("antibiotic prescription", "Healthcare", "Medications"),
    ("vitamin supplements", "Healthcare", "Medications"),
    ("maintenance medication", "Healthcare", "Medications"),
    ("blood pressure medicine", "Healthcare", "Medications"),
    ("cholesterol medication", "Healthcare", "Medications"),
    ("pain reliever purchase", "Healthcare", "Medications"),
    ("diabetes medication", "Healthcare", "Medications"),
    ("cough syrup", "Healthcare", "Medications"),
    ("allergy medicine", "Healthcare", "Medications"),
    ("fever reducer", "Healthcare", "Medications"),
    ("pharmacy receipt", "Healthcare", "Medications"),
    ("gamot sa presyon", "Healthcare", "Medications"),
    ("gamot sa ubo", "Healthcare", "Medications"),
    ("gamot sa sipon", "Healthcare", "Medications"),
    ("bitamina", "Healthcare", "Medications"),
    ("pampalakas na gamot", "Healthcare", "Medications"),
    ("gamot pang-maintenance", "Healthcare", "Medications"),
    ("reseta ng doktor", "Healthcare", "Medications"),
    ("pampagaling na gamot", "Healthcare", "Medications"),
    ("gamot sa sakit ng ulo", "Healthcare", "Medications"),
    ("eye drops purchase", "Healthcare", "Medications"),
    ("antacid tablets", "Healthcare", "Medications"),
    ("herbal supplement", "Healthcare", "Medications"),

    ("Medical checkup St. Luke's", "Healthcare", "Doctor Visits"),
    ("flu vaccine", "Healthcare", "Doctor Visits"),
    ("annual physical", "Healthcare", "Doctor Visits"),
    ("laboratory test", "Healthcare", "Doctor Visits"),
    ("blood test", "Healthcare", "Doctor Visits"),
    ("X-ray", "Healthcare", "Doctor Visits"),
    ("ultrasound", "Healthcare", "Doctor Visits"),
    ("doctor consultation", "Healthcare", "Doctor Visits"),
    ("medical checkup", "Healthcare", "Doctor Visits"),
    ("check-up sa doktor", "Healthcare", "Doctor Visits"),
    ("pagpapatingin", "Healthcare", "Doctor Visits"),
    ("konsulta", "Healthcare", "Doctor Visits"),
    ("Makati Med consultation", "Healthcare", "Doctor Visits"),
    ("Asian Hospital checkup", "Healthcare", "Doctor Visits"),
    ("Chinese General Hospital", "Healthcare", "Doctor Visits"),
    ("cardinal santos medical", "Healthcare", "Doctor Visits"),
    ("specialist consultation", "Healthcare", "Doctor Visits"),
    ("cardiologist fee", "Healthcare", "Doctor Visits"),
    ("pediatrician visit", "Healthcare", "Doctor Visits"),
    ("dermatologist consultation", "Healthcare", "Doctor Visits"),
    ("ENT doctor checkup", "Healthcare", "Doctor Visits"),
    ("neurologist appointment", "Healthcare", "Doctor Visits"),
    ("gynecologist visit", "Healthcare", "Doctor Visits"),
    ("physical therapy session", "Healthcare", "Doctor Visits"),
    ("CT scan procedure", "Healthcare", "Doctor Visits"),
    ("MRI test", "Healthcare", "Doctor Visits"),
    ("pagbisita sa espesyalista", "Healthcare", "Doctor Visits"),
    ("bayad sa doktor", "Healthcare", "Doctor Visits"),
    ("pagsusuri ng dugo", "Healthcare", "Doctor Visits"),
    ("doktor ng puso", "Healthcare", "Doctor Visits"),
    ("doktor ng balat", "Healthcare", "Doctor Visits"),
    ("pagpapa-check ng ngipin", "Healthcare", "Doctor Visits"),
    ("pagpapasuri ng katawan", "Healthcare", "Doctor Visits"),
    ("taunang medical", "Healthcare", "Doctor Visits"),
    ("COVID test", "Healthcare", "Doctor Visits"),
    ("bone density scan", "Healthcare", "Doctor Visits"),

    ("Dental cleaning", "Healthcare", "Dental Care"),
    ("Braces adjustment", "Healthcare", "Dental Care"),
    ("pasta ng ngipin", "Healthcare", "Dental Care"),
    ("teeth cleaning", "Healthcare", "Dental Care"),
    ("tooth extraction", "Healthcare", "Dental Care"),
    ("pasta sa ngipin", "Healthcare", "Dental Care"),
    ("Root canal", "Healthcare", "Dental Care"),
    ("dental checkup", "Healthcare", "Dental Care"),
    ("tooth filling", "Healthcare", "Dental Care"),
    ("pasta sa ngipin", "Healthcare", "Dental Care"),
    ("bunot ngipin", "Healthcare", "Dental Care"),
    ("linis ngipin", "Healthcare", "Dental Care"),
    ("dental implant procedure", "Healthcare", "Dental Care"),
    ("teeth whitening service", "Healthcare", "Dental Care"),
    ("dental crown installation", "Healthcare", "Dental Care"),
    ("orthodontic treatment", "Healthcare", "Dental Care"),
    ("dentist consultation fee", "Healthcare", "Dental Care"),
    ("gum treatment", "Healthcare", "Dental Care"),
    ("wisdom tooth removal", "Healthcare", "Dental Care"),
    ("dental bridge work", "Healthcare", "Dental Care"),
    ("pediatric dentist visit", "Healthcare", "Dental Care"),
    ("retainer adjustment", "Healthcare", "Dental Care"),
    ("dental x-ray", "Healthcare", "Dental Care"),
    ("pagpapaayos ng ngipin", "Healthcare", "Dental Care"),
    ("paglalagay ng pustiso", "Healthcare", "Dental Care"),
    ("pagpapakinis ng ngipin", "Healthcare", "Dental Care"),
    ("pagpapabunot ng bagang", "Healthcare", "Dental Care"),
    ("paglilinis ng gilagid", "Healthcare", "Dental Care"),
    ("regular na dental checkup", "Healthcare", "Dental Care"),
    ("pagpapagawa ng crown", "Healthcare", "Dental Care"),
    ("pagpapabunot ng sirang ngipin", "Healthcare", "Dental Care"),
    ("invisible braces payment", "Healthcare", "Dental Care"),
    ("dental anesthesia", "Healthcare", "Dental Care"),

    ("Eye checkup", "Healthcare", "Vision Care/Eyewear"),
    ("EO glasses", "Healthcare", "Vision Care/Eyewear"),
    ("Ideal Vision contact lenses", "Healthcare", "Vision Care/Eyewear"),
    ("eye examination", "Healthcare", "Vision Care/Eyewear"),
    ("contact lenses", "Healthcare", "Vision Care/Eyewear"),
    ("eyeglasses", "Healthcare", "Vision Care/Eyewear"),
    ("salamin sa mata", "Healthcare", "Vision Care/Eyewear"),
    ("contact lens", "Healthcare", "Vision Care/Eyewear"),
    ("check-up mata", "Healthcare", "Vision Care/Eyewear"),
    ("salamin", "Healthcare", "Vision Care/Eyewear"),
    ("lens", "Healthcare", "Vision Care/Eyewear"),
    ("optical shop purchase", "Healthcare", "Vision Care/Eyewear"),
    ("vision test", "Healthcare", "Vision Care/Eyewear"),
    ("eyeglass frames", "Healthcare", "Vision Care/Eyewear"),
    ("prescription sunglasses", "Healthcare", "Vision Care/Eyewear"),
    ("multifocal lenses", "Healthcare", "Vision Care/Eyewear"),
    ("anti-radiation glasses", "Healthcare", "Vision Care/Eyewear"),
    ("ophthalmologist consultation", "Healthcare", "Vision Care/Eyewear"),
    ("contact lens solution", "Healthcare", "Vision Care/Eyewear"),
    ("reading glasses", "Healthcare", "Vision Care/Eyewear"),
    ("computer glasses", "Healthcare", "Vision Care/Eyewear"),
    ("eyeglass repair", "Healthcare", "Vision Care/Eyewear"),
    ("lens replacement", "Healthcare", "Vision Care/Eyewear"),
    ("salamin panggamot", "Healthcare", "Vision Care/Eyewear"),
    ("lente ng mata", "Healthcare", "Vision Care/Eyewear"),
    ("pagsusuri ng paningin", "Healthcare", "Vision Care/Eyewear"),
    ("doktor ng mata", "Healthcare", "Vision Care/Eyewear"),
    ("salamin sa kompyuter", "Healthcare", "Vision Care/Eyewear"),
    ("contact lens pang-araw-araw", "Healthcare", "Vision Care/Eyewear"),
    ("pagkukumpuni ng salamin", "Healthcare", "Vision Care/Eyewear"),
    ("pagpalit ng frame", "Healthcare", "Vision Care/Eyewear"),
    ("progressive lens purchase", "Healthcare", "Vision Care/Eyewear"),
    
    ("Therapy session", "Healthcare", "Mental Health Services"),
    ("Psychologist consultation", "Healthcare", "Mental Health Services"),
    ("counseling session", "Healthcare", "Mental Health Services"),
    ("mental health consultation", "Healthcare", "Mental Health Services"),
    ("therapy", "Healthcare", "Mental Health Services"),
    ("psychologist", "Healthcare", "Mental Health Services"),
    ("counseling", "Healthcare", "Mental Health Services"),
    ("mental health", "Healthcare", "Mental Health Services"),
    ("psychiatric evaluation", "Healthcare", "Mental Health Services"),
    ("psychiatrist appointment", "Healthcare", "Mental Health Services"),
    ("mental wellness check", "Healthcare", "Mental Health Services"),
    ("online therapy session", "Healthcare", "Mental Health Services"),
    ("cognitive behavioral therapy", "Healthcare", "Mental Health Services"),
    ("family counseling", "Healthcare", "Mental Health Services"),
    ("couples therapy", "Healthcare", "Mental Health Services"),
    ("stress management session", "Healthcare", "Mental Health Services"),
    ("anxiety treatment", "Healthcare", "Mental Health Services"),
    ("depression medication", "Healthcare", "Mental Health Services"),
    ("mental health workshop", "Healthcare", "Mental Health Services"),
    ("psychological assessment", "Healthcare", "Mental Health Services"),
    ("pagkonsulta sa psychologist", "Healthcare", "Mental Health Services"),
    ("pagpapatingin sa psychiatrist", "Healthcare", "Mental Health Services"),
    ("pagpapagamot ng isip", "Healthcare", "Mental Health Services"),
    ("counseling para sa pamilya", "Healthcare", "Mental Health Services"),
    ("pagpapayo para sa kalusugan ng isipan", "Healthcare", "Mental Health Services"),
    ("online na therapy", "Healthcare", "Mental Health Services"),
    ("pagpapagamot sa anxiety", "Healthcare", "Mental Health Services"),
    ("gamot para sa depression", "Healthcare", "Mental Health Services"),
    ("psychological support group", "Healthcare", "Mental Health Services"),
    ("teletherapy session", "Healthcare", "Mental Health Services"),

    # Entertainment
    ("SM Cinema tickets", "Entertainment", "Movies/Shows"),
    ("Ayala Cinema movie", "Entertainment", "Movies/Shows"),
    ("movie ticket", "Entertainment", "Movies/Shows"),
    ("cinema admission", "Entertainment", "Movies/Shows"),
    ("sine", "Entertainment", "Movies/Shows"),
    ("pelikula", "Entertainment", "Movies/Shows"),

    ("concert ticket", "Entertainment", "Concert Tickets/Events"),
    ("event admission", "Entertainment", "Concert Tickets/Events"),
    ("MOA concert tickets", "Entertainment", "Concert Tickets/Events"),
    ("Araneta show tickets", "Entertainment", "Concert Tickets/Events"),
    ("concert ticket", "Entertainment", "Concert Tickets/Events"),
    ("event admission", "Entertainment", "Concert Tickets/Events"),
    ("concert", "Entertainment", "Concert Tickets/Events"),
    ("pustiso", "Entertainment", "Concert Tickets/Events"),
    ("Philippine Aren Concert", "Entertainment", "Concert Tickets/Events"),
    ("Araneta Coliseum concert", "Entertainment", "Concert Tickets/Events"),
    ("K-Pop concert", "Entertainment", "Concert Tickets/Events"),
    ("K-Pop event", "Entertainment", "Concert Tickets/Events"),
    ("P-Pop concert", "Entertainment", "Concert Tickets/Events"),
    ("P-Pop event", "Entertainment", "Concert Tickets/Events"),
    ("International Artist", "Entertainment", "Concert Tickets/Events"),
    ("International Concert", "Entertainment", "Concert Tickets/Events"),
    ("International Event", "Entertainment", "Concert Tickets/Events"),
    ("Local Artist", "Entertainment", "Concert Tickets/Events"),
    ("Local Concert", "Entertainment", "Concert Tickets/Events"),
    ("Local Event", "Entertainment", "Concert Tickets/Events"),
    ("Local Band", "Entertainment", "Concert Tickets/Events"),
    ("Local Singer", "Entertainment", "Concert Tickets/Events"),
    
    ("Steam games purchase", "Entertainment", "Gaming"),
    ("Nintendo Switch game", "Entertainment", "Gaming"),
    ("PlayStation Plus subscription", "Entertainment", "Gaming"),
    ("Xbox Game Pass", "Entertainment", "Gaming"),
    ("video game", "Entertainment", "Gaming"),
    ("game subscription", "Entertainment", "Gaming"),
    ("video games", "Entertainment", "Gaming"),
    ("laro", "Entertainment", "Gaming"),
    
    ("libangan", "Entertainment", "Hobbies"),
    ("hobby", "Entertainment", "Hobbies"),
    ("art materials", "Entertainment", "Hobbies"),
    ("art supplies", "Entertainment", "Hobbies"),
    ("craft materials", "Entertainment", "Hobbies"),
    ("BGC art supplies", "Entertainment", "Hobbies"),
    ("National Bookstore art materials", "Entertainment", "Hobbies"),
    ("hobby materials", "Entertainment", "Hobbies"),
    ("craft supplies", "Entertainment", "Hobbies"),
        ("leisure activities", "Entertainment", "Hobbies"),
    ("leisure time hobbies", "Entertainment", "Hobbies"),
    ("leisure sports", "Entertainment", "Hobbies"),
    ("leisure equipment", "Entertainment", "Hobbies"),
    ("leisure supplies", "Entertainment", "Hobbies"),
    ("leisure materials", "Entertainment", "Hobbies"),
    ("leisure tools", "Entertainment", "Hobbies"),
    ("leisure items", "Entertainment", "Hobbies"),
    ("leisure products", "Entertainment", "Hobbies"),
    ("leisure accessories", "Entertainment", "Hobbies"),
    




     # Education
    ("National Bookstore supplies", "Education", "Supplies"),
    ("School tuition fee", "Education", "Tuition"),
    ("Online course Udemy", "Education", "Courses"),
    ("Coursera subscription", "Education", "Courses"),
    ("LinkedIn Learning", "Education", "Courses"),
    ("School books", "Education", "Books"),
    ("Review center fee", "Education", "Tuition"),
    ("study materials", "Education", "Supplies"),
    ("school supplies", "Education", "Supplies"),
    ("semester payment", "Education", "Tuition"),
    ("tuition fee", "Education", "Tuition"),
    ("online learning", "Education", "Courses"),
    ("skill development course", "Education", "Courses"),
    ("textbooks", "Education", "Books"),
    ("reference materials", "Education", "Books"),
    ("bayad sa eskwela", "Education", "Tuition"),
    ("matrikula", "Education", "Tuition"),
    ("aral", "Education", "Tuition"),
    ("libro", "Education", "Books"),
    ("notebooks", "Education", "Supplies"),
    ("notebook", "Education", "Supplies"),
    ("papel", "Education", "Supplies"),
    ("online class", "Education", "Courses"),
    ("seminar", "Education", "Courses"),
    ("workshop", "Education", "Courses"),
    ("review center", "Education", "Tuition"),
    ("review materials", "Education", "Supplies"),
    ("school project", "Education", "Supplies"),
    ("school activity", "Education", "Supplies"),
    ("school event", "Education", "Supplies"),
    ("school requirement", "Education", "Supplies"),
    ("school uniform", "Education", "Supplies"),
    ("school supplies", "Education", "Supplies"),
    ("school payment", "Education", "Tuition"),
    ("school fee", "Education", "Tuition"),
    ("online course", "Education", "Courses"),
    ("online learning", "Education", "Courses"),
    ("online training", "Education", "Courses"),
    ("online seminar", "Education", "Courses"),
    ("online workshop", "Education", "Courses"),
    ("online review", "Education", "Courses"),
    ("online class", "Education", "Courses"),
    ("online education", "Education", "Courses"),
    ("online certification", "Education", "Courses"),
    ("online degree", "Education", "Courses"),
    ("online diploma", "Education", "Courses"),
    ("online training", "Education", "Courses"),
    ("online seminar", "Education", "Courses"),
    ("online workshop", "Education", "Courses"),
    ("online review", "Education", "Courses"),
    ("online class", "Education", "Courses"),

    # Personal Care entries
    ("Watsons personal items", "Personal Care", "Personal Hygiene Products"),
    ("Guardian toiletries", "Personal Care", "Personal Hygiene Products"),
    ("Bench grooming items", "Personal Care", "Personal Hygiene Products"),
    ("Salon haircut", "Personal Care", "Haircuts/Salon Services"),
    ("Hair color treatment", "Personal Care", "Haircuts/Salon Services"),
    ("Facial treatment", "Personal Care", "Skincare Products"),
    ("Sephora skincare", "Personal Care", "Skincare Products"),
    ("Anytime Fitness membership", "Personal Care", "Gym/Fitness"),
    ("Gold's Gym monthly", "Personal Care", "Gym/Fitness"),
    ("Yoga class", "Personal Care", "Gym/Fitness"),
    ("shampoo and soap", "Personal Care", "Personal Hygiene Products"),
    ("deodorant", "Personal Care", "Personal Hygiene Products"),
    ("toothpaste", "Personal Care", "Personal Hygiene Products"),
    ("face mask", "Personal Care", "Skincare Products"),
    ("toner", "Personal Care", "Skincare Products"),
    ("moisturizer", "Personal Care", "Skincare Products"),
    ("makeup", "Personal Care", "Personal Hygiene Products"),
    ("nail polish", "Personal Care", "Personal Hygiene Products"),
    ("manicure pedicure", "Personal Care", "Haircuts/Salon Services"),
    ("gym trainer", "Personal Care", "Gym/Fitness"),
    ("boxing class", "Personal Care", "Gym/Fitness"),
    ("Zumba class", "Personal Care", "Gym/Fitness"),
    ("toiletries", "Personal Care", "Personal Hygiene Products"),
    ("bathroom supplies", "Personal Care", "Personal Hygiene Products"),
    ("hair products", "Personal Care", "Personal Hygiene Products"),
    ("haircut service", "Personal Care", "Haircuts/Salon Services"),
    ("hair treatment", "Personal Care", "Haircuts/Salon Services"),
    ("skin care products", "Personal Care", "Skincare Products"),
    ("facial products", "Personal Care", "Skincare Products"),
    ("gym membership", "Personal Care", "Gym/Fitness"),
    ("fitness class", "Personal Care", "Gym/Fitness"),
    ("exercise equipment", "Personal Care", "Gym/Fitness"),
     ("shampoo at sabon", "Personal Care", "Personal Hygiene Products"),
    ("deodorant", "Personal Care", "Personal Hygiene Products"),
    ("toothbrush", "Personal Care", "Personal Hygiene Products"),
    ("gupit", "Personal Care", "Haircuts/Salon Services"),
    ("salon", "Personal Care", "Haircuts/Salon Services"),
    ("rebond", "Personal Care", "Haircuts/Salon Services"),
    ("pampaganda", "Personal Care", "Skincare Products"),
    ("facial", "Personal Care", "Skincare Products"),
    ("gym", "Personal Care", "Gym/Fitness"),
    ("zumba", "Personal Care", "Gym/Fitness"),
    ("exercise", "Personal Care", "Gym/Fitness"),
    ("Men's grooming kit", "Personal Care", "Personal Hygiene Products"),
    ("Beard trimmer", "Personal Care", "Personal Hygiene Products"),
    ("Sun protection cream", "Personal Care", "Skincare Products"),
    ("Protein supplements", "Personal Care", "Gym/Fitness"),
    ("Fitness tracker", "Personal Care", "Gym/Fitness"),
    ("Group fitness class", "Personal Care", "Gym/Fitness"),
    ("Sports massage", "Personal Care", "Haircuts/Salon Services"),
    ("Wellness workshop", "Personal Care", "Gym/Fitness"),
    ("pilates class", "Personal Care", "Gym/Fitness"),
    ("supplement", "Personal Care", "Gym/Fitness"),
    ("fitness equipment", "Personal Care", "Gym/Fitness"),
    ("yoga", "Personal Care", "Gym/Fitness"),
    ("yoga class", "Personal Care", "Gym/Fitness"),
    ("yoga instructor", "Personal Care", "Gym/Fitness"),
    ("Anytime Fitness", "Personal Care", "Gym/Fitness"),
    ("Gold's Gym", "Personal Care", "Gym/Fitness"),
    ("Pilates class", "Personal Care", "Gym/Fitness"),
    ("Fitness class", "Personal Care", "Gym/Fitness"),
    ("Sports massage", "Personal Care", "Haircuts/Salon Services"),
    
    ("lotion", "Personal Care", "Skincare Products"),
    ("baby powder", "Personal Care", "Personal Hygiene Products"),
    ("pabango", "Personal Care", "Personal Hygiene Products"),
    ("pampabango", "Personal Care", "Personal Hygiene Products"),
    ("cotton buds", "Personal Care", "Personal Hygiene Products"),
    ("bulak", "Personal Care", "Personal Hygiene Products"),
    ("sanitary napkin", "Personal Care", "Personal Hygiene Products"),
    ("napkin", "Personal Care", "Personal Hygiene Products"),
    ("pantyliner", "Personal Care", "Personal Hygiene Products"),
    ("shampoo ng bata", "Personal Care", "Personal Hygiene Products"),
    ("sabon ng bata", "Personal Care", "Personal Hygiene Products"),
    ("baby wipes", "Personal Care", "Personal Hygiene Products"),
    ("wipes", "Personal Care", "Personal Hygiene Products"),
    ("pang-ahit", "Personal Care", "Personal Hygiene Products"),
    ("razor", "Personal Care", "Personal Hygiene Products"),
    ("panglinis ng tenga", "Personal Care", "Personal Hygiene Products"),
    ("panglinis ng kuko", "Personal Care", "Personal Hygiene Products"),
    ("nail cutter", "Personal Care", "Personal Hygiene Products"),
    ("cuticle remover", "Personal Care", "Personal Hygiene Products"),
    ("pampaligo", "Personal Care", "Personal Hygiene Products"),
    ("pampaputi", "Personal Care", "Skincare Products"),
    ("pampakinis", "Personal Care", "Skincare Products"),
    ("pampaganda ng buhok", "Personal Care", "Haircuts/Salon Services"),
    ("pampakintab ng buhok", "Personal Care", "Haircuts/Salon Services"),
    ("hair oil", "Personal Care", "Haircuts/Salon Services"),
    ("hair serum", "Personal Care", "Haircuts/Salon Services"),
    ("pangkulay ng buhok", "Personal Care", "Haircuts/Salon Services"),
    ("pangkulot ng buhok", "Personal Care", "Haircuts/Salon Services"),
    ("pang-straight ng buhok", "Personal Care", "Haircuts/Salon Services"),
    ("salon treatment", "Personal Care", "Haircuts/Salon Services"),
    ("spa", "Personal Care", "Haircuts/Salon Services"),
    ("foot spa", "Personal Care", "Haircuts/Salon Services"),
    ("body scrub", "Personal Care", "Skincare Products"),
    ("facial wash", "Personal Care", "Skincare Products"),
    ("face cream", "Personal Care", "Skincare Products"),
    ("eye cream", "Personal Care", "Skincare Products"),
    ("lip balm", "Personal Care", "Skincare Products"),
    ("lip tint", "Personal Care", "Personal Hygiene Products"),
    ("makeup remover", "Personal Care", "Skincare Products"),


    

    # Family/Dependents entries
    ("Pet food Pedigree", "Family/Dependents", "Pet Care/Supplies"),
    ("Vet checkup", "Family/Dependents", "Pet Care/Supplies"),
    ("Dog grooming", "Family/Dependents", "Pet Care/Supplies"),
    ("School supplies for kids", "Family/Dependents", "School Expenses"),
    ("Daycare monthly", "Family/Dependents", "Childcare"),
    ("yayas salary", "Family/Dependents", "Childcare"),
    ("yaya advance", "Family/Dependents", "Childcare"),
    ("dog food", "Family/Dependents", "Pet Care/Supplies"),
    ("cat food", "Family/Dependents", "Pet Care/Supplies"),
    ("pet vitamins", "Family/Dependents", "Pet Care/Supplies"),
    ("school project", "Family/Dependents", "School Expenses"),
    ("school uniform", "Family/Dependents", "School Expenses"),
    ("field trip fee", "Family/Dependents", "School Expenses"),
    ("school event", "Family/Dependents", "School Expenses"),
    ("pet supplies", "Family/Dependents", "Pet Care/Supplies"),
    ("animal food", "Family/Dependents", "Pet Care/Supplies"),
    ("veterinary service", "Family/Dependents", "Pet Care/Supplies"),
    ("school materials", "Family/Dependents", "School Expenses"),
    ("educational supplies", "Family/Dependents", "School Expenses"),
    ("childcare service", "Family/Dependents", "Childcare"),
    ("babysitting fee", "Family/Dependents", "Childcare"),
    ("nanny payment", "Family/Dependents", "Childcare"),
    ("pagkain ng alagang hayop", "Family/Dependents", "Pet Care/Supplies"),
    ("pagkain ng pusa", "Family/Dependents", "Pet Care/Supplies"),
    ("pagkain ng aso", "Family/Dependents", "Pet Care/Supplies"),
    ("bayad sa yaya", "Family/Dependents", "Childcare"),
    ("sweldo ng yaya", "Family/Dependents", "Childcare"),
    ("school supplies", "Family/Dependents", "School Expenses"),
    ("uniporme", "Family/Dependents", "School Expenses"),
    ("baon", "Family/Dependents", "School Expenses"),
    ("project sa school", "Family/Dependents", "School Expenses"),
    ("gatas ni baby", "Family/Dependents", "Childcare"),
    ("pambili ng diaper ni baby", "Family/Dependents", "Childcare"),
    ("bayad sa tutor ng anak", "Family/Dependents", "School Expenses"),
    ("baon ng anak sa school", "Family/Dependents", "School Expenses"),
    ("pang-project ng anak", "Family/Dependents", "School Expenses"),
    ("pang-allowance ng anak", "Family/Dependents", "School Expenses"),
    ("pang-meryenda ng bata", "Family/Dependents", "School Expenses"),
    ("pambili ng school shoes", "Family/Dependents", "School Expenses"),
    ("pambili ng school bag", "Family/Dependents", "School Expenses"),
    ("pambili ng uniform", "Family/Dependents", "School Expenses"),
    ("pang-enroll ng anak", "Family/Dependents", "School Expenses"),
    ("pang-bayad sa yaya", "Family/Dependents", "Childcare"),
    ("panggamot ng alagang aso", "Family/Dependents", "Pet Care/Supplies"),
    ("panggamot ng alagang pusa", "Family/Dependents", "Pet Care/Supplies"),
    ("pambili ng laruan ng bata", "Family/Dependents", "Childcare"),
    ("pambili ng vitamins ng anak", "Family/Dependents", "School Expenses"),
    ("pang-birthday ng anak", "Family/Dependents", "School Expenses"),
    ("panghanda sa birthday ng bata", "Family/Dependents", "School Expenses"),
    ("pangregalo sa teacher", "Family/Dependents", "School Expenses"),
    ("pangbaon sa field trip", "Family/Dependents", "School Expenses"),


    # Insurance entries
    ("Philhealth contribution", "Insurance", "Health Insurance"),
    ("HMO premium", "Insurance", "Health Insurance"),
    ("SSS contribution", "Insurance", "Health Insurance"),
    ("Sun Life insurance", "Insurance", "Life Insurance"),
    ("AXA insurance premium", "Insurance", "Life Insurance"),
    ("Malayan insurance", "Insurance", "Home Insurance"),
    ("property insurance premium", "Insurance", "Home Insurance"),
    ("house insurance policy", "Insurance", "Home Insurance"),
    ("home protection plan", "Insurance", "Home Insurance"),
    ("fire insurance premium", "Insurance", "Home Insurance"),
    ("homeowner's insurance", "Insurance", "Home Insurance"),
    ("residential property coverage", "Insurance", "Home Insurance"),
    ("house and lot insurance", "Insurance", "Home Insurance"),
    ("dwelling protection policy", "Insurance", "Home Insurance"),
    ("condo insurance premium", "Insurance", "Home Insurance"),
    ("typhoon insurance coverage", "Insurance", "Home Insurance"),
    ("flood insurance policy", "Insurance", "Home Insurance"),
    ("earthquake insurance", "Insurance", "Home Insurance"),
    ("seguro ng bahay", "Insurance", "Home Insurance"),
    ("property damage coverage", "Insurance", "Home Insurance"),
    ("home contents insurance", "Insurance", "Home Insurance"),
    ("property protection plan", "Insurance", "Home Insurance"),
    
    # Travel Insurance entries
    ("Travel insurance for vacation", "Insurance", "Travel Insurance"),
    ("Pru Life payment", "Insurance", "Life Insurance"),
    ("Pru Life premium", "Insurance", "Life Insurance"),
    ("Manulife insurance", "Insurance", "Life Insurance"),
    ("BPI-AIA insurance", "Insurance", "Life Insurance"),
    ("car insurance annual", "Insurance", "Car Insurance"),
    ("SSS voluntary", "Insurance", "Health Insurance"),
    ("Maxicare premium", "Insurance", "Health Insurance"),
    ("Medicard payment", "Insurance", "Health Insurance"),
    ("insurance policy", "Insurance", "Life Insurance"),
    ("insurance premium", "Insurance", "Life Insurance"),
    ("insurance contribution", "Insurance", "Life Insurance"),
    ("insurance payment", "Insurance", "Life Insurance"),
    ("insurance fee", "Insurance", "Life Insurance"),
    ("insurance coverage", "Insurance", "Life Insurance"),
    ("insurance claim", "Insurance", "Life Insurance"),
    ("insurance policy", "Insurance", "Life Insurance"),
    ("insurance premium", "Insurance", "Life Insurance"),
    ("insurance contribution", "Insurance", "Life Insurance"),
     ("international travel insurance", "Insurance", "Travel Insurance"),
    ("overseas trip coverage", "Insurance", "Travel Insurance"),
    ("travel protection plan", "Insurance", "Travel Insurance"),
    ("flight insurance premium", "Insurance", "Travel Insurance"),
    ("vacation insurance policy", "Insurance", "Travel Insurance"),
    ("travel medical insurance", "Insurance", "Travel Insurance"),
    ("journey coverage plan", "Insurance", "Travel Insurance"),
    ("seguro sa biyahe", "Insurance", "Travel Insurance"),
    ("travel cancellation insurance", "Insurance", "Travel Insurance"),
    ("baggage loss protection", "Insurance", "Travel Insurance"),
    ("trip delay coverage", "Insurance", "Travel Insurance"),
    ("travel insurance for family", "Insurance", "Travel Insurance"),
    ("outbound travel protection", "Insurance", "Travel Insurance"),
    ("insurance sa pagbibiyahe", "Insurance", "Travel Insurance"),
    ("overseas insurance coverage", "Insurance", "Travel Insurance"),
    



     # Savings & Investments (expanded significantly)
    ("Bank of the Philippine Islands deposit", "Savings & Investments", "Retirement"),
    ("Metrobank time deposit", "Savings & Investments", "Investments"),
    ("Security Bank investment", "Savings & Investments", "Investments"),
    ("UITF investment", "Savings & Investments", "Investments"),
    ("Stock market purchase", "Savings & Investments", "Investments"),
    ("Mutual fund contribution", "Savings & Investments", "Investments"),
    ("Emergency fund deposit", "Savings & Investments", "Emergency Fund"),
    ("Retirement account contribution", "Savings & Investments", "Retirement"),
    ("Personal savings transfer", "Savings & Investments", "Savings Goals"),
    ("COL Financial stock buy", "Savings & Investments", "Investments"),
    ("First Metro Securities trading", "Savings & Investments", "Investments"),
    ("SSS voluntary contribution", "Savings & Investments", "Retirement"),
    ("PERA account deposit", "Savings & Investments", "Retirement"),
    ("Bonds investment", "Savings & Investments", "Investments"),
    ("Cryptocurrency investment", "Savings & Investments", "Investments"),
    ("Money market fund", "Savings & Investments", "Investments"),
    ("Investment trust fund", "Savings & Investments", "Investments"),
    ("Pagibig MP2 savings", "Savings & Investments", "Savings Goals"),
    ("iSave account deposit", "Savings & Investments", "Savings Goals"),
    ("alkansya deposit", "Savings & Investments", "Savings Goals"),
    ("ipon sa bangko", "Savings & Investments", "Savings Goals"),
    ("pamuhunan", "Savings & Investments", "Investments"),
    ("retirement fund", "Savings & Investments", "Retirement"),
    ("emergency savings", "Savings & Investments", "Emergency Fund"),
    ("savings account", "Savings & Investments", "Savings Goals"),
    ("personal savings", "Savings & Investments", "Savings Goals"),
    ("stock market", "Savings & Investments", "Investments"),
    ("mutual fund", "Savings & Investments", "Investments"),
    ("bonds", "Savings & Investments", "Investments"),
    ("cryptocurrency", "Savings & Investments", "Investments"),
    ("money market", "Savings & Investments", "Investments"),
    ("investment trust", "Savings & Investments", "Investments"),
    ("pag-ibig savings", "Savings & Investments", "Savings Goals"),
    ("alkansya", "Savings & Investments", "Savings Goals"),
    ("ipon", "Savings & Investments", "Savings Goals"),
    ("investment", "Savings & Investments", "Investments"),
    ("investment account", "Savings & Investments", "Investments"),
    ("investment portfolio", "Savings & Investments", "Investments"),
    ("investment strategy", "Savings & Investments", "Investments"),
    ("investment vehicle", "Savings & Investments", "Investments"),
    ("investment opportunity", "Savings & Investments", "Investments"),
    ("investment return", "Savings & Investments", "Investments"),
    ("investment risk", "Savings & Investments", "Investments"),
    ("investment performance", "Savings & Investments", "Investments"),
    ("investment growth", "Savings & Investments", "Investments"),
    ("investment loss", "Savings & Investments", "Investments"),
    ("investment gain", "Savings & Investments", "Investments"),
    ("investment income", "Savings & Investments", "Investments"),
    ("investment capital", "Savings & Investments", "Investments"),
    ("investment fund", "Savings & Investments", "Investments"),
    ("investment account", "Savings & Investments", "Investments"),
    ("investment portfolio", "Savings & Investments", "Investments"),
    ("investment strategy", "Savings & Investments", "Investments"),
    ("investment vehicle", "Savings & Investments", "Investments"),
    ("investment opportunity", "Savings & Investments", "Investments"),
    ("investment return", "Savings & Investments", "Investments"),
    ("bonus deposit", "Savings & Investments", "Savings Goals"),
    ("year-end bonus", "Savings & Investments", "Savings Goals"),
    ("performance bonus", "Savings & Investments", "Savings Goals"),
    ("13th month bonus", "Savings & Investments", "Savings Goals"),
    ("bonus savings", "Savings & Investments", "Savings Goals"),
    ("bonus investment", "Savings & Investments", "Investments"),
    ("bonus fund transfer", "Savings & Investments", "Savings Goals"),
    ("bonus allocation", "Savings & Investments", "Savings Goals"),
    ("bonus contribution", "Savings & Investments", "Retirement"),
    ("bonus retirement fund", "Savings & Investments", "Retirement"),
    
    # Shopping entries
    ("Uniqlo clothes", "Shopping", "Clothing"),
    ("H&M purchase", "Shopping", "Clothing"),
    ("Zara shopping", "Shopping", "Clothing"),
    ("SM Store clothes", "Shopping", "Clothing"),
    ("Landmark department store", "Shopping", "Clothing"),
    ("SM Appliance center", "Shopping", "Electronics"),
    ("Abenson appliance", "Shopping", "Electronics"),
    ("Lazada order", "Shopping", "Electronics"),
    ("Shopee purchase", "Shopping", "Electronics"),
    ("Mandaue Foam furniture", "Shopping", "Home Decor"),
    ("SM Home items", "Shopping", "Home Decor"),
    ("Christmas gift shopping", "Shopping", "Gifts"),
    ("Birthday present", "Shopping", "Gifts"),
    ("Divisoria shopping", "Shopping", "Clothing"),
    ("Taytay tiangge", "Shopping", "Clothing"),
    ("Greenhills shopping", "Shopping", "Electronics"),
    ("cellphone load", "Bills & Utilities", "Phone Plan"),
    ("birthday regalo", "Shopping", "Gifts"),
    ("Christmas exchange gift", "Shopping", "Gifts"),
    ("clothing purchase", "Shopping", "Clothing"),
    ("shoes shopping", "Shopping", "Clothing"),
    ("accessories", "Shopping", "Clothing"),
    ("electronic device", "Shopping", "Electronics"),
    ("gadget purchase", "Shopping", "Electronics"),
    ("home furniture", "Shopping", "Home Decor"),
    ("household items", "Shopping", "Home Decor"),
    ("gift purchase", "Shopping", "Gifts"),
    ("present shopping", "Shopping", "Gifts"),
    ("damit", "Shopping", "Clothing"),
    ("sapatos", "Shopping", "Clothing"),
    ("tsinelas", "Shopping", "Clothing"),
    ("gadyet", "Shopping", "Electronics"),
    ("appliance", "Shopping", "Electronics"),
    ("kagamitan", "Shopping", "Electronics"),
    ("muwebles", "Shopping", "Home Decor"),
    ("gamit bahay", "Shopping", "Home Decor"),
    ("regalo", "Shopping", "Gifts"),
    ("pasalubong", "Shopping", "Gifts"),
    ("aguinaldo", "Shopping", "Gifts"),

    # Contingency Fund entries
    ("emergency home repair", "Contingency Fund", "Emergency Repairs"),
    ("unexpected plumbing issue", "Contingency Fund", "Emergency Repairs"),
    ("roof leak repair", "Contingency Fund", "Emergency Repairs"),
    ("electrical system emergency", "Contingency Fund", "Emergency Repairs"),
    ("broken pipe fix", "Contingency Fund", "Emergency Repairs"),
    ("urgent home maintenance", "Contingency Fund", "Emergency Repairs"),
    ("emergency electrician", "Contingency Fund", "Emergency Repairs"),
    ("urgent aircon repair", "Contingency Fund", "Emergency Repairs"),
    ("immediate house repair", "Contingency Fund", "Emergency Repairs"),
    ("tubero emergency", "Contingency Fund", "Emergency Repairs"),
    ("biglang sira bubong", "Contingency Fund", "Emergency Repairs"),
    ("emergency repair bahay", "Contingency Fund", "Emergency Repairs"),
    ("sudden gate malfunction", "Contingency Fund", "Emergency Repairs"),
    ("water heater breakdown", "Contingency Fund", "Emergency Repairs"),
    ("emergency power outage fix", "Contingency Fund", "Emergency Repairs"),
    ("ceiling collapse repair", "Contingency Fund", "Emergency Repairs"),
    ("flood damage restoration", "Contingency Fund", "Emergency Repairs"),
    ("emergency door replacement", "Contingency Fund", "Emergency Repairs"),
    ("window emergency fix", "Contingency Fund", "Emergency Repairs"),
    ("sudden bathroom leak", "Contingency Fund", "Emergency Repairs"),
    ("kitchen sink emergency", "Contingency Fund", "Emergency Repairs"),
    ("toilet overflow repair", "Contingency Fund", "Emergency Repairs"),
    ("pagkasira ng gripo", "Contingency Fund", "Emergency Repairs"),
    ("biglang tagas ng tubig", "Contingency Fund", "Emergency Repairs"),
    ("emergency na problema sa kuryente", "Contingency Fund", "Emergency Repairs"),
    ("biglang baha sa bahay", "Contingency Fund", "Emergency Repairs"),
    ("kagyat na pagkukumpuni", "Contingency Fund", "Emergency Repairs"),
    ("sira ng pinto", "Contingency Fund", "Emergency Repairs"),
    ("pagkawala ng kuryente", "Contingency Fund", "Emergency Repairs"),
    ("emergency gate repair", "Contingency Fund", "Emergency Repairs"),
    ("biglang pagkasira ng bubong", "Contingency Fund", "Emergency Repairs"),
    ("pagkasira ng tubo", "Contingency Fund", "Emergency Repairs"),
    ("biglang pagkasira ng pader", "Contingency Fund", "Emergency Repairs"),

    ("emergency room visit", "Contingency Fund", "Medical Emergencies"),
    ("urgent care clinic", "Contingency Fund", "Medical Emergencies"),
    ("emergency medicine purchase", "Contingency Fund", "Medical Emergencies"),
    ("ambulance service", "Contingency Fund", "Medical Emergencies"),
    ("sudden illness treatment", "Contingency Fund", "Medical Emergencies"),
    ("unexpected medical procedure", "Contingency Fund", "Medical Emergencies"),
    ("emergency dental work", "Contingency Fund", "Medical Emergencies"),
    ("accident medical expense", "Contingency Fund", "Medical Emergencies"),
    ("emergency hospital admission", "Contingency Fund", "Medical Emergencies"),
    ("biglang karamdaman", "Contingency Fund", "Medical Emergencies"),
    ("emergency sa ospital", "Contingency Fund", "Medical Emergencies"),
    ("aksidente medical expense", "Contingency Fund", "Medical Emergencies"),
    ("sudden eye injury treatment", "Contingency Fund", "Medical Emergencies"),
    ("emergency surgery procedure", "Contingency Fund", "Medical Emergencies"),
    ("unforeseen specialist consultation", "Contingency Fund", "Medical Emergencies"),
    ("emergency medicine delivery", "Contingency Fund", "Medical Emergencies"),
    ("urgent medical transportation", "Contingency Fund", "Medical Emergencies"),
    ("immediate health diagnostic", "Contingency Fund", "Medical Emergencies"),
    ("emergency COVID treatment", "Contingency Fund", "Medical Emergencies"),
    ("unexpected allergy reaction", "Contingency Fund", "Medical Emergencies"),
    ("biglang pagkalagnat", "Contingency Fund", "Medical Emergencies"),
    ("emergency na operasyon", "Contingency Fund", "Medical Emergencies"),
    ("hindi inaasahang pagkakasakit", "Contingency Fund", "Medical Emergencies"),
    ("agarang pagpapagamot", "Contingency Fund", "Medical Emergencies"),
    ("biglang pangangailangan ng ambulansya", "Contingency Fund", "Medical Emergencies"),
    ("urgent na pagpapaospital", "Contingency Fund", "Medical Emergencies"),
    ("emergency blood test", "Contingency Fund", "Medical Emergencies"),
    ("emergency MRI scan", "Contingency Fund", "Medical Emergencies"),
    ("emergency heart condition", "Contingency Fund", "Medical Emergencies"),
    ("unexpected medical test", "Contingency Fund", "Medical Emergencies"),
    ("immediate medical procedure", "Contingency Fund", "Medical Emergencies"),
    ("emergency medication", "Contingency Fund", "Medical Emergencies"),

    ("unexpected car breakdown", "Contingency Fund", "Unexpected Expenses"),
    ("stolen wallet replacement", "Contingency Fund", "Unexpected Expenses"),
    ("sudden travel expense", "Contingency Fund", "Unexpected Expenses"),
    ("emergency accommodation", "Contingency Fund", "Unexpected Expenses"),
    ("unexpected tax payment", "Contingency Fund", "Unexpected Expenses"),
    ("sudden family emergency", "Contingency Fund", "Unexpected Expenses"),
    ("unplanned legal expense", "Contingency Fund", "Unexpected Expenses"),
    ("emergency fund withdrawal", "Contingency Fund", "Unexpected Expenses"),
    ("urgent document processing", "Contingency Fund", "Unexpected Expenses"),
    ("unexpected penalty fee", "Contingency Fund", "Unexpected Expenses"),
    ("biglang gastos", "Contingency Fund", "Unexpected Expenses"),
    ("hindi inaasahang bayarin", "Contingency Fund", "Unexpected Expenses"),
    ("emergency na gastusin", "Contingency Fund", "Unexpected Expenses"),
    ("di-inaasahang gastos", "Contingency Fund", "Unexpected Expenses"),
    ("computer repair emergency", "Contingency Fund", "Unexpected Expenses"),
    ("smartphone replacement", "Contingency Fund", "Unexpected Expenses"),
    ("laptop screen repair", "Contingency Fund", "Unexpected Expenses"),
    ("urgent appliance replacement", "Contingency Fund", "Unexpected Expenses"),
    ("unexpected travel cancellation", "Contingency Fund", "Unexpected Expenses"),
    ("emergency visa processing", "Contingency Fund", "Unexpected Expenses"),
    ("biglang pagkakasakit", "Contingency Fund", "Medical Emergencies"),
    ("unexpected gadget repair", "Contingency Fund", "Unexpected Expenses"),
    ("emergency passport renewal", "Contingency Fund", "Unexpected Expenses"),
    ("surprise government fee", "Contingency Fund", "Unexpected Expenses"),
    ("urgent replacement ID", "Contingency Fund", "Unexpected Expenses"),
    ("sudden water damage to devices", "Contingency Fund", "Unexpected Expenses"),
    ("emergency pet treatment", "Contingency Fund", "Unexpected Expenses"),
    ("unexpected school requirement", "Contingency Fund", "Unexpected Expenses"),
    ("urgent bank transaction fee", "Contingency Fund", "Unexpected Expenses"),
    ("last-minute uniform purchase", "Contingency Fund", "Unexpected Expenses"),
    ("emergency phone replacement", "Contingency Fund", "Unexpected Expenses"),
    ("unplanned flight change fee", "Contingency Fund", "Unexpected Expenses"),
    ("sudden lost baggage replacement", "Contingency Fund", "Unexpected Expenses"),
    ("emergency cash advance need", "Contingency Fund", "Unexpected Expenses"),
    ("unforeseen moving expense", "Contingency Fund", "Unexpected Expenses"),
    ("pagkawala ng cellphone", "Contingency Fund", "Unexpected Expenses"),
    ("biglang pagkasira ng laptop", "Contingency Fund", "Unexpected Expenses"),
    ("hindi inaasahang bayarin sa gobyerno", "Contingency Fund", "Unexpected Expenses"),
    ("biglaang pagkakansela ng biyahe", "Contingency Fund", "Unexpected Expenses"),
    ("emergency pagpapaayos ng gadget", "Contingency Fund", "Unexpected Expenses"),
    ("pagkawala ng pitaka", "Contingency Fund", "Unexpected Expenses"),
    ("biglaang pagkasira ng sasakyan", "Contingency Fund", "Unexpected Expenses"),
    ("hindi planadong gastusin", "Contingency Fund", "Unexpected Expenses"),
    ("emergency na bayarin", "Contingency Fund", "Unexpected Expenses"),
    ("kagyat na kagamitan", "Contingency Fund", "Unexpected Expenses"),
    ("rush passport renewal", "Contingency Fund", "Unexpected Expenses"),
    ("urgent NBI clearance", "Contingency Fund", "Unexpected Expenses"),
    ("emergency house pest control", "Contingency Fund", "Unexpected Expenses"),
    ("sudden refrigerator breakdown", "Contingency Fund", "Unexpected Expenses"),
    ("urgent legal document fee", "Contingency Fund", "Unexpected Expenses"),
    ("flash flood recovery", "Contingency Fund", "Unexpected Expenses"),

    
    ("gatas ng bata", "Food & Groceries", "Groceries"),
    ("diaper", "Food & Groceries", "Groceries"),
    ("gatas at tinapay", "Food & Groceries", "Groceries"),
    ("bigas na binili", "Food & Groceries", "Groceries"),
    ("ulam sa palengke", "Food & Groceries", "Groceries"),
    ("pamalengke", "Food & Groceries", "Groceries"),
    ("pambili ng gulay", "Food & Groceries", "Groceries"),
    ("pambili ng prutas", "Food & Groceries", "Groceries"),
    ("pambili ng itlog", "Food & Groceries", "Groceries"),
    ("pambili ng gatas", "Food & Groceries", "Groceries"),
    ("pambili ng tinapay", "Food & Groceries", "Groceries"),
    ("pambili ng mantika", "Food & Groceries", "Groceries"),
    ("pambili ng asukal", "Food & Groceries", "Groceries"),
    ("pambili ng kape", "Food & Groceries", "Groceries"),
    ("pambili ng delata", "Food & Groceries", "Groceries"),
    ("pambili ng noodles", "Food & Groceries", "Groceries"),
    ("pambili ng sabong panlaba", "Food & Groceries", "Groceries"),
    ("pambili ng sabong panligo", "Food & Groceries", "Groceries"),
    ("pambili ng toyo", "Food & Groceries", "Groceries"),
    ("pambili ng suka", "Food & Groceries", "Groceries"),
    ("pambili ng asin", "Food & Groceries", "Groceries"),
    ("pambili ng paminta", "Food & Groceries", "Groceries"),
    ("pambili ng bawang", "Food & Groceries", "Groceries"),
    ("pambili ng sibuyas", "Food & Groceries", "Groceries"),
    ("pambili ng hotdog", "Food & Groceries", "Groceries"),
    ("pambili ng tocino", "Food & Groceries", "Groceries"),
    ("pambili ng longganisa", "Food & Groceries", "Groceries"),
    ("pambili ng itlog", "Food & Groceries", "Groceries"),
    ("pambili ng tinapa", "Food & Groceries", "Groceries"),
    ("pambili ng sardinas", "Food & Groceries", "Groceries"),
    ("pambili ng gatas ng bata", "Food & Groceries", "Groceries"),
    ("pambili ng diaper", "Food & Groceries", "Groceries"),
    ("pambili ng snacks", "Food & Groceries", "Groceries"),
    ("baon ng bata", "Food & Groceries", "Groceries"),
    ("pambaon sa school", "Food & Groceries", "Groceries"),
    ("pambaon ng anak", "Food & Groceries", "Groceries"),
]
class ExpenseClassifier:
    def __init__(self, training_data):
        """Initialize the classifier with training data"""
        try:
            self.training_data = training_data
            self.vectorizer = TfidfVectorizer(ngram_range=(1, 3))

            # Prepare training texts and labels
            self.texts = [entry[0] for entry in training_data]
            self.categories = [entry[1] for entry in training_data]
            self.expense_types = [entry[2] for entry in training_data]

            # Fit vectorizer
            self.tfidf_matrix = self.vectorizer.fit_transform(self.texts)
            print("Classifier initialized successfully")
        except Exception as e:
            print(f"Error initializing classifier: {e}")
            raise

    def preprocess_text(self, text):
        """Preprocess input text"""
        try:
            # Convert to lowercase
            text = text.lower()
            # Remove punctuation
            text = text.translate(str.maketrans('', '', string.punctuation))
            # Tokenize
            tokens = word_tokenize(text)
            # Remove stopwords
            stop_words = set(stopwords.words('english'))
            tokens = [token for token in tokens if token not in stop_words]
            return ' '.join(tokens)
        except Exception as e:
            print(f"Error in preprocess_text: {e}")
            raise

    def classify_expense(self, user_input):
        """Classify user input into category and expense type"""
        try:
            # Preprocess input
            processed_input = self.preprocess_text(user_input)
            # Vectorize input
            input_vector = self.vectorizer.transform([processed_input])
            # Calculate similarities
            similarities = cosine_similarity(input_vector, self.tfidf_matrix).flatten()
            # Get best match
            best_match_idx = np.argmax(similarities)
            confidence_score = float(similarities[best_match_idx])
            
            return {
                'user_input': user_input,
                'category': self.categories[best_match_idx],
                'expense_type': self.expense_types[best_match_idx],
                'confidence_score': confidence_score,
                'requires_new_expense_type': confidence_score < 0.3
            }
        except Exception as e:
            print(f"Error in classify_expense: {e}")
            print(f"Input text: {user_input}")
            print(traceback.format_exc())
            raise

app = Flask(__name__)
CORS(app)

# Initialize classifier globally
try:
    classifier = ExpenseClassifier(training_data)
    print("Global classifier initialized")
except Exception as e:
    print(f"Error initializing global classifier: {e}")
    sys.exit(1)

@app.route('/classify_expense', methods=['POST'])
def classify_expense():
    try:
        data = request.get_json()
        if not data:
            return jsonify({'error': 'No JSON data received'}), 400
        
        expense_text = data.get('expense_text')
        if not expense_text:
            return jsonify({'error': 'No expense_text provided'}), 400

        print(f"Received request to classify: {expense_text}")
        
        result = classifier.classify_expense(expense_text)
        similar_entries = []  # We'll skip similar entries for now to simplify debugging
        
        response = {
            'classification': result,
            'similar_entries': similar_entries
        }
        
        print(f"Successful classification: {response}")
        return jsonify(response)

    except Exception as e:
        print(f"Error processing request: {e}")
        print(traceback.format_exc())
        return jsonify({
            'error': 'Internal server error',
            'message': str(e)
        }), 500

@app.route('/', methods=['GET'])
def health_check():
    return jsonify({"status": "healthy"})

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 10000))
    app.run(host='0.0.0.0', port=port)